CREATE TABLE "Files" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"Status"	TEXT NOT NULL,
	"CreatedTime"	TEXT NOT NULL,
	"LastModifiedTime"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
)